name: Deploy Monorepo Node.js App to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.15.0"

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use 22.15.0

            cd excali-draw

            git pull origin main

            # Create global .env
            echo "${{ secrets.GLOBAL_ENV }}" > .env

            # Create app-specific .env files
            echo "${{ secrets.BACKEND_ENV }}" > apps/backend/.env
            echo "${{ secrets.WEB_ENV }}" > apps/web/.env
            echo "${{ secrets.WS_ENV }}" > apps/ws/.env
            echo "${{ secrets.DATABASE_ENV }}" > packages/database/.env

            # check the directory
            ls
            
            # Install dependencies
            pnpm install

            # Build the Turborepo
            pnpm run build

            # Restart existing processes
            pm2 restart excali-http || pm2 start "pnpm --dir apps/http-backend start" --name excali-http
            pm2 restart excali-ws   || pm2 start "pnpm --dir apps/ws-backend start" --name excali-ws
            pm2 restart excali-fe   || pm2 start "pnpm --dir apps/web-backend start" --name excali-fe

            pm2 save
